export const colorClassMap = {
  indigo: {
    bg: 'bg-indigo-500',
    borderBase: 'border-indigo-500',
    border: 'hover:border-indigo-500',
    'hc-text': 'text-indigo-600',
    'lc-text': 'bg-indigo-200',
    text: 'text-indigo-500',
    decoration: 'decoration-indigo-500',
  },
  blue: {
    bg: 'bg-blue-500',
    borderBase: 'border-blue-500',
    border: 'hover:border-blue-500',
    'hc-text': 'text-blue-600',
    'lc-text': 'bg-blue-200',
    text: 'text-blue-500',
    decoration: 'decoration-blue-500',
  },
  red: {
    bg: 'bg-red-500',
    borderBase: 'border-red-500',
    border: 'hover:border-red-500',
    'hc-text': 'text-red-600',
    'lc-text': 'bg-red-200',
    text: 'text-red-500',
    decoration: 'decoration-red-500',
  },
  green: {
    bg: 'bg-green-500',
    borderBase: 'border-green-500',
    border: 'hover:border-green-500',
    'hc-text': 'text-green-600',
    'lc-text': 'bg-green-200',
    text: 'text-green-500',
    decoration: 'decoration-green-500',
  },
  yellow: {
    bg: 'bg-yellow-500',
    borderBase: 'border-yellow-500',
    border: 'hover:border-yellow-500',
    'hc-text': 'text-yellow-600',
    'lc-text': 'bg-yellow-200',
    text: 'text-yellow-500',
    decoration: 'decoration-yellow-500',
  },
  pink: {
    bg: 'bg-pink-500',
    borderBase: 'border-pink-500',
    border: 'hover:border-pink-500',
    'hc-text': 'text-pink-600',
    'lc-text': 'bg-pink-200',
    text: 'text-pink-500',
    decoration: 'decoration-pink-500',
  },
  purple: {
    bg: 'bg-purple-500',
    borderBase: 'border-purple-500',
    border: 'hover:border-purple-500',
    'hc-text': 'text-purple-600',
    'lc-text': 'bg-purple-200',
    text: 'text-purple-500',
    decoration: 'decoration-purple-500',
  }
}